# banner
banner:
  charset: UTF-8
  location: classpath:banner.txt

# logger
logging:
  level:
    root: INFO
    org:
      hibernate: INFO

# redis
redis:
  keyPrefix: ajisai_
  redisCache:
    host: localhost
    port: 6379

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8080

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ajisai?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: test
    password: test
    initialize: false
    max-active: 10
    max-idle: 8
    min-idle: 8
    initial-size: 10
    test-on-borrow: true
    validation-query: SELECT 1
    remove-abandoned: true
    remove-abandoned-timeout: 60

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
  data:
    jpa:
      repositories:
        enabled: true
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
myconfig:
   types:
      - type 1
      - type 2
      - type 3